# TODO fix functions directory error on netlify

[build.environment]
  NODE_VERSION = "18"

[build]
  publish = ".next"
  command = "pnpm run build"

[functions]
  directory = "functions/"

[dev]
  command = "pnpm dev"
  port = "8888"
  publish = ".next"